version: '3.4'

services:
  # customerdb:
  #   container_name: customerdb
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=admin1234
  #     - POSTGRES_DB=Customerdb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
     container_name: rabbitmq
     restart: always
     ports:
        - "5672:5672"
        - "15672:15672"

  # pgadmin:
  #   container_name: pgadmin
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin1234
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - pgadmin_data:/root/.pgadmin/

  # customer.api:
  #   container_name: customer.api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development      
  #   ports:
  #     - "8001:8080"
